name: SonarCloud
on:
  push:
    branches: [ 'main' ]
    tags: [ v* ]
jobs:
  sonarcloud:
    name: SonarCloud scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        run: |
          echo github.repository
        
      
